version: 2
updates:
  # Frontend dependencies (npm)
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "your-github-username"
    labels:
      - "frontend"
      - "dependencies"

  # Backend dependencies (npm)
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "your-github-username"
    labels:
      - "backend"
      - "dependencies"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    reviewers:
      - "your-github-username"
    labels:
      - "ci-cd"
      - "dependencies"
