name: Frontend Quality and Performance Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
  run: npx eslint .

    - name: Run Stylelint
      run: npx stylelint '**/*.{css,scss}'

    - name: Run Prettier
      run: npx prettier --check '**/*.{js,jsx,ts,tsx,html,css,scss}'

    - name: Run TypeScript compiler
      run: npx tsc --noEmit

    - name: Run Jest tests
      run: npm test -- --coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3

    - name: Check dependencies
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  performance:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Run Lighthouse CI
      uses: treosh/lighthouse-ci-action@v9
      with:
        configPath: './lighthouserc.json'
        uploadArtifacts: true

    - name: Run webpack-bundle-analyzer
      run: npx webpack-bundle-analyzer --mode static --report report.html ./dist/stats.json

    - name: Upload bundle analysis
      uses: actions/upload-artifact@v3
      with:
        name: bundle-analysis
        path: report.html
